### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [adam7tt/prj-rev-bwfs-dasmoto#1]
You want to split your HTML up into sections by wrapping related tags in div tags:
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/40812245-c269bbee-6502-11e8-9a23-b71cce5c83d1.png">
This makes your code more readable and easier to style.

https://github.com/adam7tt/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L10-L13

**Comment by adam7tt** [comment]
I believe I have edited it to be more appropriate
